language: csharp
dist: trusty
notifications:
  email: never
env:
- ASPNETCORE_ENVIRONMENT=Development
mono: none
dotnet: 2.1.503
script:
  - dotnet restore -v Minimal
  - dotnet build src/SodaPop.ConfigExplorer.csproj -c Release
  - dotnet test tests/SodaPop.ConfigExplorer.Tests.csproj
