language: csharp
dist: trusty
notifications:
  email: never
env:
- ASPNETCORE_ENVIRONMENT=Development
mono: none
dotnet: 1.0.1
script:
  - dotnet restore -v Minimal
  - dotnet build src/AspNetOptionsExplorer.csproj -c Release 
  - dotnet test tests/AspNetOptionsExplorer.Tests.csproj