trigger:
- master
pr:
  - master

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

stages:
  - stage: Build
    jobs:
      - job:
        displayName: "Building and Test"
        strategy:
          matrix:
            Windows:
              vmImage: 'windows-latest'
            Ubuntu:
              vmImage: 'ubuntu-latest'
            Mac:
              vmImage: 'macOS-latest'
        pool:
          vmImage: $(vmImage)
        steps:
          - task: UseDotNet@2
            displayName: "Install and setup the version of SDK in global.json"
            inputs:
              packageType: 'sdk'
              useGlobalJson: true
          - task: DotNetCoreCLI@2
            displayName: "Build Solution"
            inputs:
              command: build
              arguments: '-c $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: "Test"
            inputs:
              command: test
              arguments: '-c $(buildConfiguration) --collect "Code Coverage"'
          - task: DotNetCoreCLI@2
            displayName: "Pack Nuget"
            inputs:
              command: pack
              arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: drop
  - stage: Deploy
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    jobs:
      - deployment: 
        environment: Nuget
        strategy:
            runOnce:
              deploy:
                steps:
                - task: NuGetCommand@2
                  displayName: 'NuGet push'
                  inputs:
                    command: 'push'
                    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
                    nuGetFeedType: 'external'
                    publishFeedCredentials: 'Nuget.Org'