trigger:
- master
pr:
  - master

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  
stages:
  - stage: Build
    jobs:
        - job:
          displayName: "Building API and Website"
          pool:
            vmImage: 'windows-latest'
          steps:
            - task: UseDotNet@2
              displayName: "Install and setup the version of SDK in global.json"
              inputs:
                packageType: 'sdk'
                useGlobalJson: true
